//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineClothStore.db
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Product
    {
        public int Product_Id { get; set; }

        [Required]
        [Display(Name = "Product Name")]
        public string Product_Name { get; set; }

        
        [Display(Name = "Product Image")]
        public string Product_Image { get; set; }

        [Required]
        [Display(Name = "Category Name")]
        public Nullable<int> Category_ID { get; set; }

        [Required]
        [Display(Name = "Product Price")]
        public Nullable<int> Product_Price { get; set; }

        [Required]
        [Display(Name = "Product Quantity")]
        public Nullable<int> Product_Quantity { get; set; }
    
        public virtual Category Category { get; set; }

        //public HttpPostedFileBase ImageFile { get; set; }
    }
}
